name       : haskell-data-array-byte
version    : 0.1.0.1
release    : 1
source     :
    - https://hackage.haskell.org/package/data-array-byte-0.1.0.1/data-array-byte-0.1.0.1.tar.gz : 1bb6eca0b3e02d057fe7f4e14c81ef395216f421ab30fdaa1b18017c9c025600
license    : BSD-3-Clause
component  : programming.haskell
summary    : Compatibility layer for Data.Array.Byte
description: |
    Compatibility layer for Data.Array.Byte, providing boxed wrappers for ByteArray# and MutableByteArray# and relevant instances for GHC < 9.4.
builddeps  :
    - ghc-devel
setup      : |
    %haskell_configure
build      : |
    %haskell_build
install    : |
    %haskell_install
    %haskell_register
